# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 7.x version
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#phpwomen"
